site_name: Claimlane Returns, Refunds & Warranty Portal BRD
docs_dir: brd
site_url: https://charanbobby.github.io/ClaimLaneRequirementsRepo/
use_directory_urls: false

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md

  - About:
      - Overview & Purpose: overview-purpose.md
      - Scope: scope.md
      - Actors: actors.md

  - Process:
      - High-Level Process Flow: process-high-level.md

  - Requirements:
      - Functional: functional-requirements.md
      - Non-Functional: non-functional-requirements.md
      - Business Rules: business-rules.md
      - Changelog: changelog.md
      - Phase 2 Backlog: phase-2-backlog.md

  - Stories:
      - Epics & User Stories: epics-user-stories.md

  - Reference:
      - Appendices: appendices.md

extra_css:
  - css/giscus.css

extra_javascript:
  - js/giscus.js
 
